---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-newdef-sept12
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-newdef-sept12 
  name: test-newdef-sept12
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi